-- Migration number: 0001 	 2023-04-09T08:43:57.485Z
-- Autogenerated by Superflare. Do not edit this file directly.
CREATE TABLE words (
  id INTEGER PRIMARY KEY,
  text TEXT NOT NULL,
  createdAt DATETIME NOT NULL,
  updatedAt DATETIME NOT NULL
);